### ISSUE TITLE
🧹 Spring cleanup

### ISSUE THREAD

**Issue by florimondmanca** [bocadilloproject/bocadillo#236]
Do you feel Bocadillo has expanded too much? That it has accumulated bloat? Or that it hast lost focus? I do!

I've been having doubts about how massive the Bocadillo code base and documentation have become.

I have a feeling there are many features that were added just for the sake of it, yet they're not actually used by anyone.

So, time for a spring cleanup 💐

Features I don't think are necessary and should be removed:

- [x] [#245] Named routes and `url_for()`: we're not aiming at building template-based/MVT applications, yet that's the main area where I'd see those useful. But these features include a lot of complexity; some currently open issues would just disappear if they were removed.
- [x] [#241] `res.media` and the whole "media" thing. It's been called `media` to represent an abstraction layer: JSON is a format among others, and we could in theory support YAML, MessagePack, etc… Yet, who builds APIs out of YAML? Out of MessagePack? Most web services use JSON.
- ~[ ] Default `HTTPError` handler being text: it should be JSON.~
- [x] [#239] `app.run()`: it forces to use `if __name__ == "__main__"` which is both ugly and beginner-averse, with little advantages compared to the `uvicorn` command.
- [x] [#239] Debug mode: if we remove `app.run()`, its only use is a) to enable hot reload and b) to display tracebacks in the browser. a) is covered by `uvicorn --reload`. I don't think b) is actually useful.
- [x] [#238] Synchronous stuff: Bocadillo is an async web framework, after all, so why support both sync and async versions of stuff (views, hooks, error handlers…) when all-async does the trick?
- [x] [Queso](https://bocadilloproject.github.io/queso/) (the CLI): unless we find a very good use for it, if `app.run()` is removed then Queso has no reason to exist anymore.

All these features have a poor developer need vs. implementation complexity balance. They create more problems for *us* to solve than they solve developers' problems.

Also, because of the lack on focus on REST, implementing incredibly useful stuff such as data validation (#8) and API documentation (#122, #125) is so much more difficult, because we need to make a distinction between REST endpoints and other HTTP endpoints.

Anyway, I'd be more than happy to have anyone's feedback on features they think are not necessary, hinder productivity or developer experience, or seem unclear!

**Comment by cs01** [comment]
My experience with bocadillo is a fairly narrow use-case, so my responses will be based on that. (The project is https://github.com/cs01/termpair)

> Templates: the only use for templates I've personally found (and seen in others' projects) is to use it to serve a frontend app's index.html, or any HTML page that is actually not a Jinja-templated page.

I like the built in tempates, and use it to pass data from the server to the client. My use case is generally to pass a Python dict to the frontend and store it as some initial JavaScript data in the page. I am surprised nobody is using Jinja templates. 

> res.media and the whole "media" thing. It's been called media to represent an abstraction layer: JSON is a format among others, and we could in theory support YAML, MessagePack, etc… Yet, who builds APIs out of YAML? Out of MessagePack? Most web services use JSON.

Agreed about yaml, I think that should be removed. I haven't used media personally so have no opinion besides removing yaml.

> Default HTTPError handler being text: it should be JSON.

No opinion here

> Hooks: do you even know what they are/what they're for? I never had a practical use of it. Maybe it's just me.

Just looked these up. They seem pretty cool, but would probably apply to larger projects. Probably wouldn't be a big deal to developers if they were removed, and might be worth it if it saves bocadillo dev's substantial mental overhead.

> app.run(): it forces to use if __name__ == "__main__" which is both ugly and beginner-averse, with little advantages compared to the uvicorn command.

What is the uvicorn command? In Flask and sometimes Bocadillo I was sometimes confused as to where parameters went: in the App() instantiation or in the run() call.

> Debug mode: if we remove app.run(), its only use is a) to enable hot reload and b) to display tracebacks in the browser. a) is covered by uvicorn --reload. I don't think b) is actually useful.

Agreed

> Synchronous stuff: Bocadillo is an async web framework, after all, so why support both sync and async versions of stuff (views, hooks, error handlers…) when all-async does the trick?

I suppose if folks want synchronous they can use Flask or one of the other frameworks out there. If you go all-async, I suggest making the docs very explicit and friendly about how to convert synchronous code to async code with some examples of common patterns users might be looking for.

> Queso (the CLI): unless we find a very good use for it, if app.run() is removed then Queso has no reason to exist anymore.

To be honest I do not know what queso does. I looked at https://bocadilloproject.github.io/queso/reference/#overview and couldn't quickly tell what it does or why I'd want it. If it is something like [click-web](https://github.com/fredrik-corneliusson/click-web), I think that would be interesting!

Things I love about Bocadillo:
* built in websocket support (flask doesn't have this)
* built in compression (flask didn't have this last time I used it, not sure if it does now)
* excellent documentation (it is as good or better than Flask's)
* friendly/responsive community
* clean APIs and patterns

I haven't spent too much time building web apps lately, but I know things I wanted in the past were: dead simple ways to create REST API's with validation built in (like django-rest-framework) and auto-documentation (swagger/open API). Also easy GraphQL support seems really interesting because of how powerful GraphQL is.

Why did you build Bocadillo in the first place? For fun? To learn? To be the go-to GraphQL-friendly web framework? Or most database-friendly? Or an async Flask replacement to be the go-to web framework for everyone? Knowing your mission and target audience might help you keep focus on the project.

**Comment by florimondmanca** [comment]
Thanks a ton for your thorough write up @cs01. Gathering feedback and user needs is exactly what I need at the moment to move Bocadillo forward. :+1:

---

> I like the built in tempates, and use it to pass data from the server to the client. My use case is generally to pass a Python dict to the frontend and store it as some initial JavaScript data in the page. I am surprised nobody is using Jinja templates.

I see! I was probably over the top to consider removing Jinja templates. It's quite a self-contained feature after all, and it can be useful for prototyping.

That said, I'm more concerned about [named routes](https://bocadilloproject.github.io/guides/http/routing.html#naming-routes) and [URL reversal](https://bocadilloproject.github.io/guides/http/routing.html#reversing-named-routes) — i.e. `app.url_for()`. It adds a lot of complexity because it's the only reason apps and routes need to have a name. In templates, the alternative is to use the full path, e.g. `/foo/{{ some_param }}`.

Do you think this feature has been/would be useful to you?

> Agreed about yaml, I think that should be removed. I haven't used media personally so have no opinion besides removing yaml.

YAML isn't included by default; we just have a [how-to guide](https://bocadilloproject.github.io/how-to/yaml-media.html#yaml-media-serialization) on adding YAML media handlers. But yeah, I think we should keep things simple and introduce `res.json = ...`, which would also be a much more straight-forward API IMO.

> What is the uvicorn command?

It's the CLI command provided by the [uvicorn](https://github.com/encode/uvicorn) ASGI web server. `app.run()` is merely a wrapper around that command that sets flags based on app configuration and keyword arguments.

> In Flask and Bocadillo I was sometimes confused as to where parameters went: in the App() instantiation or in the run() call.

I actually share the same feeling. I've been working on #230 which brings configuration via a single entrypoint (`app.configure()`), and adds a global `settings` object accessible from anywhere in the code base as soon as an app has been configured. Feel like this could help relieve the confusion?

> I suppose if folks want synchronous they can use Flask or one of the other frameworks out there. If you go all-async, I suggest making the docs very explicit and friendly about how to convert synchronous code to async code with some examples of common patterns users might be looking for (as you have been doing 😄).

Absolutely! We should definitely add some friendly hints on getting started with async. Adding patterns and conversion examples is a very good idea!

> To be honest I do not know what queso does.

Yes, exactly. I initially envisioned Queso to be a development toolkit for Bocadillo (so not a similar thing to `click-web`), but now it seems like a distraction from improving the framework itself. I'm not even sure that building dev tools should be something to aim for — ideally Bocadillo should be simple enough to use that we shouldn't need any extra tooling, right?

> Things I love about Bocadillo:

Thank you so much for sharing this list! 🙏 Means a lot to me, plus it always helps to know what parts of the framework people really like. :-)

> Dead simple ways to create REST API's with validation built in (like django-rest-framework) and auto-documentation (swagger/open API)

We have #122 and #125 open for the autodoc part, which I agree would be a huge benefit. Data validation is also on the agenda — #8. FastAPI has both of these, and people seem to *really* like it. I'd love to see these in land Bocadillo too!

> Also easy GraphQL support seems really interesting because of how powerful GraphQL is.

Yep, we also have an issue open for that: #220. The Python async GraphQL space seems to be evolving at the moment, so I'll sure be watching for potential integrations. Be sure to check out the issue if you have any recommendations/thoughts. :-)

> Why did you build Bocadillo in the first place?

I initially built Bocadillo to learn about Python async and web frameworks, and also for fun. I didn't have an actual *product vision* at the start, e.g. "let's build an async version of Flask", and I've been working on building a clearer one lately.

But I like this way to put things: " the go-to async web framework for everyone". I think that's quite close to what I'd like to see Bocadillo become: a framework that makes building async web stuff so obvious it could be someone's first framework, but also ensures power users get (mostly) all the features they need to be productive. The thing is, this means Bocadillo needs to include a *lot* of stuff to be usable, and I can see how there's a risk of losing focus in the process.

**Comment by EricE** [comment]
> Absolutely! We should definitely add some friendly hints on getting started with async. Adding patterns and conversion examples is a very good idea!

A couple of votes for this.  I am pretty new to asyncio and web development so I'm struggling a bit with how a site would be architected.  Based on my current understanding all the first level handling of user input would be async from the framework and you want to minimize synchronous code to keep the site responsive.  If an input triggers extensive processing, you would need to either hand it off using multiprocesssing or sprinkle in asyncio.sleep(0) in the synchronous code.  Using threads isn't desirable if you are CPU bound and if the processing is I/O intensive it seems like you would just use asnycio?

**Comment by florimondmanca** [comment]
Okay, I've moved this "all-async" thing to its own issue so we can tackle it later: #238.

@EricE: Yes, asyncio (and single-threaded task-based concurrency in general) wasn't built with high CPU loads in mind — quite the opposite in fact: it's made for I/O-intensive applications that can keep the CPU available for switching between tasks as they finish I/O operations.

Now, I can understand how async can be confusing — especially for folks who also get started in web development.

We have some documentation [here](https://bocadilloproject.github.io/getting-started/#an-async-web-framework) and [there](https://bocadilloproject.github.io/getting-started/#what-if-i-don-t-do-async) on async in Bocadillo. Did you find that useful? Are these pieces of docs not visible enough? Should they contain more information on *app architecture*, as you said?

**Comment by florimondmanca** [comment]
Okay, `app.run()` and debug mode no longer exist: #240 🎉

**Comment by cs01** [comment]
I have personally not used named routes, nor do I think I ever have on my other projects. Seems like a 20% use case. (A rule of thumb I read somewhere is that 20% of features are used by 80% of  users, the remaining 20% of users use the other 80% of features.)

> ideally Bocadillo should be simple enough to use that we shouldn't need any extra tooling, right?

Yes that idea is probably out of scope for Bocadillo core, but would be a cool project to make with Bocadillo!

> The thing is, this means Bocadillo needs to include a lot of stuff to be usable, and I can see how there's a risk of losing focus in the process

Sounds like a good goal! Would it make sense to capture a list of everything Flask does, prioritize, then implement each thing, one-by-one, in Bocadillo?

A few months ago I saw your announcement tweet about Bocadillo in response to Kenneth's tweet when he started responder, so I have been following from the very start. I have been really impressed with what you have created and honestly don't really know how you made it all so quickly. I think the project deserves more attention and :star: s.

**Comment by EricE** [comment]
I had read the links you provided and they are useful if you have a broad enough sense of how you would use an async web framework.  When I read 
>"WSGI was not designed to handle multiple clients at a time — a property known as concurrency. If processing a request requires running a 10-second long database 
query, other clients have to wait, period." 

then it sounds like most websites should be async to maintain a responsive UI.

In my case, I have some tasks for a site that involve lots of REST queries, number crunching, database accesses and page generation.  I'd like to kick off the REST queries and the rest, go to another activity on the site, be notified that the task is done, go back to it, etc.  Clearly the REST queries are perfect for async, but that is only a part of what is going on.  So how do you balance the async parts with the sync parts, i.e. how much has to be async before you should use Bocadillo over Flask.  Are the async web frameworks just designed to grab a little data from a database and spit it out as JSON or to be an alternate to Flask for general purpose sites?

I have done asyncio apps with Tkinter and am looking to move to a web interface.  I was attracted to Responder and then Bocadillo since it looked more full featured.  I have a number of sites I'd like to create for personal and side projects at work and most of them have elements of time consuming tasks where the rest of the site/UI should stay responsive.  For reference, I think I am a solid intermediate Python programmer but I do electronics for robots in my day job.  Probably doesn't matter but I'm also mostly a Windows user since most EE and ME CAD tools are still Windows only.

For "app architecture", I think the above could cover it.  I looked at #238 and it looks good but I would add a "d." (or expand "c.") that talks about how to mix async with sync if you do have CPU intensive operations.  It looks like there is good coverage with async database libraries but there are still plenty of libraries that don't have async replacements.  Also, some words on using a Javascript framework like Vue with Bocadillo would be welcome if it is appropriate :)

Your responsiveness is wonderful!

**Comment by cs01** [comment]
> . Also, some words on using a Javascript framework like Vue with Bocadillo would be welcome if it is appropriate :)

I second this, but for React. My go-to stack is Python backend+React frontend. So some kind of instructions or boilerplate code would be helpful I think. I can probably add docs for this if you want. Another thing I liked was the Docker examples to get Bocadillo running. Expanding on that might be nice, like example systemd files.

**Comment by florimondmanca** [comment]
> I'd like to kick off the REST queries and the rest, go to another activity on the site, be notified that the task is done, go back to it, etc.

@EricE I think this kind of logic must be figured out the frontend side. It sounds like an advanced frontend architecture (in Angular you’d use observables for this, in Vue I’m not sure how this would be done) and I don’t think Bocadillo can do much more — Bocadillo itself is already asynchronous so it will be able to manage the multiple requests you’d make on the frontend. :-)

> Are the async web frameworks just designed to grab a little data from a database and spit it out as JSON or to be an alternate to Flask for general purpose sites?

They can do so much more than exposing JSON over web endpoints! The “async” part just refers to the execution model. It unlocks superpowers like WebSocket (which Flask does not support) for bidirectional communication with clients. You can check out @cs01’s [TermPair](https://github.com/cs01/termpair) project as an example, and also the official [tutorial](https://bocadilloproject.github.io/getting-started/tutorial.html). 😄

**Comment by florimondmanca** [comment]
^ Duh, misclick on the close button.

> Also, some words on using a Javascript framework like Vue with Bocadillo would be welcome if it is appropriate :)

Absolutely! I’m also interested in investigating this because Python/JS is my favorite backend/frontend stack as well. I’m more of a Vue user at the moment, but I’d love to have your input on setting up a Bocadillo/React project, @cs01. I think setting up an example repo people could fork (or a cookie cutter?) could be a good way to take this off.

> Your responsiveness is wonderful!

My pleasure! 😄

**Comment by florimondmanca** [comment]
> Seems like a 20% use case.

Agreed @cs01. I’m trying to cut the long trail with this spring cleanup, and url_for() does seem to be part of it. :)

> Would it make sense to capture a list of everything Flask does, prioritize, then implement each thing, one-by-one, in Bocadillo?

Never thought of that, but I think the experiment could be worthwhile. I think we already cover a lot, but that would give better visibility. :)

> I have been really impressed with what you have created and honestly don't really know how you made it all so quickly. I think the project deserves more attention and ⭐️ s.

Thank you so much! 👏 If you have any ideas to help spread the Bocadillo love, I’m all ears! I’ve been wanting to write some blog posts, but no time available unfortunately. I think publishing an “Introducing Bocadillo” post once 0.14 is out (lots of improvements in there) and cross-posting it to Medium could help.

**Comment by florimondmanca** [comment]
Quick update: 400 LOC just vanished out of existence. `url_for()` and named routes are now gone! #248

**Comment by florimondmanca** [comment]
Final update: Queso has retired! https://github.com/bocadilloproject/queso https://pypi.org/project/queso

Spring cleanup complete. 🧹✨ Thanks for participating!
